package com.example.vato.opguitar.database;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.vato.opguitar.database.Preset;
import com.example.vato.opguitar.database.PresetProperty;

import com.example.vato.opguitar.database.PresetDao;
import com.example.vato.opguitar.database.PresetPropertyDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig presetDaoConfig;
    private final DaoConfig presetPropertyDaoConfig;

    private final PresetDao presetDao;
    private final PresetPropertyDao presetPropertyDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        presetDaoConfig = daoConfigMap.get(PresetDao.class).clone();
        presetDaoConfig.initIdentityScope(type);

        presetPropertyDaoConfig = daoConfigMap.get(PresetPropertyDao.class).clone();
        presetPropertyDaoConfig.initIdentityScope(type);

        presetDao = new PresetDao(presetDaoConfig, this);
        presetPropertyDao = new PresetPropertyDao(presetPropertyDaoConfig, this);

        registerDao(Preset.class, presetDao);
        registerDao(PresetProperty.class, presetPropertyDao);
    }
    
    public void clear() {
        presetDaoConfig.getIdentityScope().clear();
        presetPropertyDaoConfig.getIdentityScope().clear();
    }

    public PresetDao getPresetDao() {
        return presetDao;
    }

    public PresetPropertyDao getPresetPropertyDao() {
        return presetPropertyDao;
    }

}
