package com.example.vato.opguitar.database;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "PRESET".
 */
public class Preset {

    private Long id;
    /** Not-null value. */
    private String preset;

    // KEEP FIELDS - put your custom fields here
    public Preset(String preset) {
        this.preset = preset;
    }
    // KEEP FIELDS END

    public Preset() {
    }

    public Preset(Long id) {
        this.id = id;
    }

    public Preset(Long id, String preset) {
        this.id = id;
        this.preset = preset;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getPreset() {
        return preset;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPreset(String preset) {
        this.preset = preset;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
