package com.example.vato.opguitar.database;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.vato.opguitar.database.PresetProperty;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PRESET_PROPERTY".
*/
public class PresetPropertyDao extends AbstractDao<PresetProperty, Long> {

    public static final String TABLENAME = "PRESET_PROPERTY";

    /**
     * Properties of entity PresetProperty.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property PresetId = new Property(1, int.class, "presetId", false, "PRESET_ID");
        public final static Property Option = new Property(2, int.class, "option", false, "OPTION");
        public final static Property Value = new Property(3, int.class, "value", false, "VALUE");
    };


    public PresetPropertyDao(DaoConfig config) {
        super(config);
    }
    
    public PresetPropertyDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PRESET_PROPERTY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"PRESET_ID\" INTEGER NOT NULL ," + // 1: presetId
                "\"OPTION\" INTEGER NOT NULL ," + // 2: option
                "\"VALUE\" INTEGER NOT NULL );"); // 3: value
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PRESET_PROPERTY\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, PresetProperty entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getPresetId());
        stmt.bindLong(3, entity.getOption());
        stmt.bindLong(4, entity.getValue());
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public PresetProperty readEntity(Cursor cursor, int offset) {
        PresetProperty entity = new PresetProperty( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // presetId
            cursor.getInt(offset + 2), // option
            cursor.getInt(offset + 3) // value
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, PresetProperty entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setPresetId(cursor.getInt(offset + 1));
        entity.setOption(cursor.getInt(offset + 2));
        entity.setValue(cursor.getInt(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(PresetProperty entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(PresetProperty entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
